.PHONY:


# ==============================================================================
# Make local SSL Certificate
# ==============================================================================

make_cert:
	echo "Generating SSL certificates"
	sh ./gateway/ssl/instructions.sh
