.PHONY:

# ==============================================================================
# Generate swagger documentation
# ==============================================================================
swagger_users_api:
	echo "Starting swagger generating"
	swag init -g **/**/*.go
